version: '3'

services: 
    nginx:
        image: nginx:latest
        volumes:
            - ./frontend/:/var/frontend/
            - ./backend/:/var/backend/
            - ./nginx/:/etc/nginx/conf.d
        ports: 
            - 80:80
        depends_on:
          - backend
    postgres:
        image: postgres:13.3
        restart: always
        environment: 
            POSTGRES_PASSWORD: test
            POSTGRES_USER: test
            POSTGRES_DB: test
        ports:
            - 3338:3338
        volumes: 
            - ./dump:/docker-entrypoint-initdb.d/
    backend:
        build:
            context: .
            dockerfile: ./docker/DockerFileBackend
        depends_on:
            - postgres
        volumes: 
            - ./backend:/backend
        restart: unless-stopped
        command: symfony server:start
        ports:
        - 2000:8000
        stdin_open: true
        tty: true
    frontend:
        build:
            context: .
            dockerfile: ./docker/DockerFileFrontend
        volumes: 
            - ./frontend:/frontend
        restart: unless-stopped
        command: npm run start
        ports:
        - 3000:3000
        stdin_open: true
        tty: true